#!/usr/bin/env ruby
require 'yaml'

# Functions

# Collect directory entries for a list
def dirEntries(location)
  Dir.entries(location).select {|entry| File.directory? File.join(location,entry) and !(entry =='.' || entry == '..') }
end

# Logic

# Acquire the levels available and properly format for whiptail
levels = dirEntries('../levels')
levels = levels.flat_map { |x| [x, "level"] }

# Level Select
levelchoice = `whiptail --title "Level" --menu "Choose level:" 30 50 20 #{levels.join(" ")} 3>&2 2>&1 1>&3`
level = YAML.load_file("../levels/#{levelchoice}/#{levelchoice}-properties.yml")

# Acquire the Challenges available and properly format for whiptail
challenges = dirEntries('../challenges')
challenges = challenges.flat_map { |x| [x, "challenge"] }

# Ask the user how many Core Challenges per Area
numcore = `whiptail --title "Core Challenges" --menu "How many Core Challenges per Area?" 30 50 20\
  "1" "One per Area"\
  "2" "Two per Area"\
  "3" "Three per Area"\
  "4" "Four per Area"\
  "5" "Five per Area" 3>&2 2>&1 1>&3`

# Determine Core Challenges per Area
corechallenges = Array.new(level["areas"].to_i) { Array.new(numcore.to_i, "")}
i = 0
while i < level["areas"].to_i do
  numcore.to_i.times do |core|
    corechallenges[i][core] = `whiptail --title "Core Challenges" --menu "Choose a challenge for Area #{i + 1}" 30 50 20\
  #{challenges.join(" ")} 3>&2 2>&1 1>&3`
  end

  i += 1
end

# Determine Edge Challenges
edgechallenges = Array.new(level["areas"].to_i) { |x| "" }
i = 0
while i < level["areas"].to_i do
  edgechallenges[i] = `whiptail --title "Edge Challenges" --menu "Choose a challenge for Area #{i + 1}" 30 50 20\
  #{challenges.join(" ")} 3>&2 2>&1 1>&3`

  i += 1
end

# Supply configuration name
configname = `whiptail --title "Configuration Name" --inputbox "Please supply a configuration name:" 10 40 3>&1 1>&2 2>&3`

# Confirm changes with user
commit = `whiptail --title "Confirm" --yesno "Commit changes?" 10 30 3>&1 1>&2 2>&3`

if commit
  puts "Config name:  #{configname}"
  puts "Map:  #{level["mapname"]}"
  puts "Filename:  #{level["filename"]}"
  puts "Areas:  #{level["areas"]}"
  puts "Number of Challenges per Area:  #{numcore}"

  puts "Core Challenges:"
  i = 0
  while i < corechallenges.length do
    puts "Area #{i + 1}"
    corechallenges[i].each {|x| puts x}
    i += 1
  end

  puts "Edge Challenges:"
  edgechallenges.each {|x| puts "Challenge:  #{x}"}

  puts "Hacklifts:  #{level["hacklifts"].join(" ")}"
else
  puts "Cancelling setup"
  exit
end
