#!/usr/bin/env bash

# Confirm changes with user
whiptail --yesno "Commit changes?" 10 30
COMMIT=$?

if [ $COMMIT -eq 0 ]; then
  echo "Committing changes..."
else
  echo "Cancelling setup"
  exit
fi
